name: ci

on:
  push:
    branches:
      - trinity
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  pull_request:
    branches:
      - trinity
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'

jobs:
  build-linux:
    name: Build Linux ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04

          - arch: arm64
            runner: ubuntu-22.04-arm

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install make gcc g++ libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build release
      run: make -j$(nproc) ARCH=${{ matrix.arch }}

    - name: Build debug
      run: |
        make clean ARCH=${{ matrix.arch }}
        make debug -j$(nproc) ARCH=${{ matrix.arch }}
